services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - default
      - dokploy-network

networks:
  default:
    attachable: true
  dokploy-network:
    external: true
